In [4]:
import numpy as np
import cv2 as cv

In [64]:
img = cv.imread('C:/Users/sanya/Downloads/cK1tuAJa6j8.jpg')
assert img is not None, "file could not be read, check with os.path.exists()"

In [8]:
img

array([[[ 67,  66,  52],
        [ 68,  67,  53],
        [ 71,  68,  53],
        ...,
        [202, 187, 161],
        [208, 193, 167],
        [208, 193, 167]],

       [[ 72,  71,  57],
        [ 72,  71,  57],
        [ 75,  72,  58],
        ...,
        [201, 186, 160],
        [202, 187, 161],
        [202, 187, 161]],

       [[ 79,  75,  64],
        [ 79,  76,  62],
        [ 82,  76,  63],
        ...,
        [199, 184, 158],
        [198, 183, 157],
        [198, 183, 157]],

       ...,

       [[ 76, 106, 111],
        [ 75, 105, 110],
        [ 75, 104, 109],
        ...,
        [ 50,  64,  62],
        [ 72,  86,  84],
        [ 67,  81,  79]],

       [[ 77, 107, 112],
        [ 76, 106, 111],
        [ 75, 104, 109],
        ...,
        [ 91, 105, 103],
        [ 70,  84,  82],
        [ 66,  80,  78]],

       [[ 79, 109, 114],
        [ 78, 108, 113],
        [ 76, 105, 110],
        ...,
        [ 52,  65,  63],
        [ 61,  74,  72],
        [ 58,  71,  69]]

In [9]:
px = img[100, 100]
print(px)

[15 23 22]


In [10]:
blue = img[100,100,0]
print(blue)

15


In [11]:
img[100, 100] = [255,255, 255]
print(img[100,100])

[255 255 255]


In [12]:
img.item(10,10,2)

61

In [13]:
img.itemset((10,10,2),100)
img.item(10,10,2)

100

In [14]:
print( img.shape )

(187, 250, 3)


In [15]:
print( img.size )

140250


In [16]:
print( img.dtype )

uint8


In [68]:
cv.imshow('img',img)
k = cv.waitKey(0)

In [60]:
print( img.shape )

(187, 250, 3)


In [95]:
morda = img[10:130, 70:150]

cv.imshow('img',morda)
k = cv.waitKey(0)

In [61]:
b, g, r = cv.split(img)
img = cv.merge((b,g,r))

In [78]:
x = np.uint8([250])
y = np.uint8([10])

print( cv.add(x,y) )

[[260.]
 [  0.]
 [  0.]
 [  0.]]


In [79]:
print( x+y )

[4]


In [94]:
img2 = cv.imread('C:/Users/sanya/Downloads/YUz0rNTkkPI.jpg')
assert img is not None, "file could not be read, check with os.path.exists()"
#C:\Users\sanya\Downloads/YUz0rNTkkPI.jpg

dst = cv.addWeighted(img,0.7,img2,0.3,0)

cv.imshow('dst',dst)
cv.waitKey(0)
cv.destroyAllWindows()

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:661: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'


In [84]:
print(img2.shape)

(502, 604, 3)


In [85]:
new_img = img2[0:187, 0:250]

In [86]:
new_img.shape

(187, 250, 3)

In [90]:
dst = cv.addWeighted(img,0.7,new_img,0.9,0)

cv.imshow('dst',dst)
cv.waitKey(0)
cv.destroyAllWindows()

In [96]:
# Load two images
img = cv.imread('C:/Users/sanya/Downloads/cK1tuAJa6j8.jpg')
img2 = cv.imread('C:/Users/sanya/Downloads/YUz0rNTkkPI.jpg')
assert img is not None, "file could not be read, check with os.path.exists()"
img2 = img2[0:187, 0:250]

# I want to put logo on top-left corner, So I create a ROI
rows,cols,channels = img2.shape
roi = img[0:rows, 0:cols]

# Now create a mask of logo and create its inverse mask also
img2gray = cv.cvtColor(img2,cv.COLOR_BGR2GRAY)
ret, mask = cv.threshold(img2gray, 10, 255, cv.THRESH_BINARY)
mask_inv = cv.bitwise_not(mask)

# Now black-out the area of logo in ROI
img1_bg = cv.bitwise_and(roi,roi,mask = mask_inv)

# Take only region of logo from logo image.
img2_fg = cv.bitwise_and(img2,img2,mask = mask)

# Put logo in ROI and modify the main image
dst = cv.add(img1_bg,img2_fg)
img[0:rows, 0:cols ] = dst

cv.imshow('res',img)
cv.waitKey(0)
cv.destroyAllWindows()